# Generated by Django 5.0.2 on 2024-05-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cultural_group',
            field=models.CharField(default='', max_length=50),
        ),
    ]
