# Generated by Django 5.0.2 on 2024-05-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_cultural_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cultural_group',
            field=models.CharField(max_length=50),
        ),
    ]
